apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram
  region: us-east-2

nodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
#    ami: auto

#cloudWatch:
    #clusterLogging:
        # enable specific types of cluster control plane logs
        #enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
